# https://coolors.co/palette/10002b-240046-3c096c-5a189a-7b2cbf-9d4edd-c77dff-e0aaff
format = """
[î‚¶](#240046)\
$username\
[î‚°](bg:#3C096C fg:#240046)\
$directory\
[î‚°](fg:#3C096C bg:#5A189A)\
$git_branch\
$git_status\
[î‚°](fg:#5A189A bg:#7B2CBF)\
$nodejs\
$c\
$golang\
$java\
$rust\
[î‚°](fg:#7B2CBF bg:#9D4EDD)\
$docker_context\
[î‚°](fg:#9D4EDD bg:#C77DFF)\
$time\
[î‚° ](fg:#C77DFF)\
"""

# Disable the blank line at the start of the prompt
add_newline = false

# You can also replace your username with a neat symbol like ï„  to save some space
[username]
show_always = true
style_user = "bg:#240046"
style_root = "bg:#240046"
format = '[$user ]($style)'

[directory]
style = "bg:#3C096C"
format = "[ $path ]($style)"
truncation_length = 5
truncation_symbol = "â€¦/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "ïœ˜ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "
# Keep in mind that the order matters. For example:
# "Important Documents" = " ïœ˜ï„ª "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important ïœ˜ " = " ïœ˜ï„ª "

[nodejs]
symbol = "îœ˜"
style = "bg:#7B2CBF"
format = '[ $symbol ($version) ]($style)'

[c]
symbol = "î˜ "
style = "bg:#7B2CBF"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = "ïŒˆ "
style = "bg:#9D4EDD"
format = '[ $symbol $context ]($style) $path'

[git_branch]
symbol = "ï˜"
style = "bg:#5A189A"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#5A189A"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = "î˜§ "
style = "bg:#7B2CBF"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = "î‰– "
style = "bg:#7B2CBF"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = "î¨"
style = "bg:#7B2CBF"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bold bg:#C77DFF"
# format = '[ ï‘ $time ]($style)'
format = '[ ğŸ˜ˆ ]($style)'
