format = """
[](#240046)\
$username\
[](bg:#3C096C fg:#240046)\
$directory\
[](fg:#3C096C bg:#5A189A)\
$git_branch\
$git_status\
[](fg:#5A189A bg:#7B2CBF)\
$nodejs\
$c\
$golang\
$java\
$rust\
[](fg:#7B2CBF bg:#9D4EDD)\
$docker_context\
[](fg:#9D4EDD bg:#C77DFF)\
$time\
[ ](fg:#C77DFF)\
"""

# Disable the blank line at the start of the prompt
add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#240046"
style_root = "bg:#240046"
format = '[$user ]($style)'

[directory]
style = "bg:#3C096C"
format = "[ $path ]($style)"
truncation_length = 5
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[nodejs]
symbol = ""
style = "bg:#7B2CBF"
format = '[ $symbol ($version) ]($style)'

[c]
symbol = " "
style = "bg:#7B2CBF"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#9D4EDD"
format = '[ $symbol $context ]($style) $path'

[git_branch]
symbol = ""
style = "bg:#5A189A"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#5A189A"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#7B2CBF"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#7B2CBF"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#7B2CBF"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#C77DFF"
format = '[  $time ]($style)'
